#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: doc/pl_PL.ISO8859-2/books/handbook/x11/Makefile,v 1.1 2006/09/24 18:59:05 hrs Exp $
#

CHAPTERS= 	x11/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
