# $FreeBSD: doc/pl_PL.ISO8859-2/articles/Makefile,v 1.1 2006/11/10 11:37:24 therek Exp $

SUBDIR =
SUBDIR+= dialup-firewall
SUBDIR+= filtering-bridges
SUBDIR+= new-users

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
