# $FreeBSD: doc/en_US.ISO8859-1/Makefile,v 1.2 2007/05/19 20:23:56 therek Exp $

SUBDIR = articles
SUBDIR+= books

COMPAT_SYMLINK = en

DOC_PREFIX?= ${.CURDIR}/..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
