# $FreeBSD: doc/pl_PL.ISO8859-2/articles/dialup-firewall/Makefile,v 1.1 2002/09/26 17:51:18 blackend Exp $

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS= article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
