# $FreeBSD: doc/pl_PL.ISO8859-2/articles/dialup-firewall/Makefile,v 1.1 2006/11/10 11:37:27 therek Exp $

DOC?= article

FORMATS?= html

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

SRCS= article.sgml

DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
