# $FreeBSD: doc/pl_PL.ISO8859-2/Makefile,v 1.2 2006/11/26 16:43:38 hrs Exp $

SUBDIR = articles
SUBDIR+= books

COMPAT_SYMLINK = pl

DOC_PREFIX?= ${.CURDIR}/..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
