# $FreeBSD: doc/pl_PL.ISO8859-2/Makefile,v 1.1 2006/11/10 11:36:40 therek Exp $

SUBDIR = articles
#SUBDIR+= books

COMPAT_SYMLINK = pl

DOC_PREFIX?= ${.CURDIR}/..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
