# $FreeBSD: doc/pl_PL.ISO8859-2/books/Makefile,v 1.1 2006/11/10 11:43:19 therek Exp $
# Original revision: 1.14

#SUBDIR+= arch-handbook
#SUBDIR+= corp-net-guide
#SUBDIR+= design-44bsd
#SUBDIR+= dev-model
#SUBDIR+= developers-handbook
#SUBDIR+= faq
#SUBDIR+= fdp-primer
SUBDIR = handbook
#SUBDIR+= pmake
#SUBDIR+= porters-handbook

ROOT_SYMLINKS= faq handbook

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
