#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: doc/pl_PL.ISO8859-2/books/handbook/desktop/Makefile,v 1.1 2006/11/10 11:46:09 therek Exp $
#

CHAPTERS= 	desktop/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
